name: finalassign
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-0 <4.0.0'

dependencies:
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_ui_auth: ^1.14.0
  firebase_ui_oauth_google: ^1.3.2
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  flutter_datetime_picker: ^1.5.0
  cloud_firestore: ^4.17.5
  intl: ^0.19.0
  table_calendar: ^3.0.0
  firebase_storage: ^11.7.7
  image_picker: ^1.1.2
  google_maps_flutter: ^2.6.1
  google_maps_flutter_web: ^0.5.7
  geocoding: ^3.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/main.jpg
