// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDrXEjwGBhimwsOAEZ8IL0pCfQ17CICVI',
    appId: '1:998273304023:web:a0fc12a77d4d9adb0e7792',
    messagingSenderId: '998273304023',
    projectId: 'finalassign-b9b78',
    authDomain: 'finalassign-b9b78.firebaseapp.com',
    storageBucket: 'finalassign-b9b78.appspot.com',
    measurementId: 'G-62R2DKKD7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv1BcJihdQ2rFPScIJi24yB94_ECo743E',
    appId: '1:998273304023:android:003e5770ba24dcf60e7792',
    messagingSenderId: '998273304023',
    projectId: 'finalassign-b9b78',
    storageBucket: 'finalassign-b9b78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeDPPhOG7TWwFJA_ZWr56MjfsUJAwNyPo',
    appId: '1:998273304023:ios:32074fb2c58871e20e7792',
    messagingSenderId: '998273304023',
    projectId: 'finalassign-b9b78',
    storageBucket: 'finalassign-b9b78.appspot.com',
    iosBundleId: 'com.example.finalassign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDrXEjwGBhimwsOAEZ8IL0pCfQ17CICVI',
    appId: '1:998273304023:web:38f6c6926f5330e80e7792',
    messagingSenderId: '998273304023',
    projectId: 'finalassign-b9b78',
    authDomain: 'finalassign-b9b78.firebaseapp.com',
    storageBucket: 'finalassign-b9b78.appspot.com',
    measurementId: 'G-0WXBBKKYM9',
  );
}
